Output "/tmp/fonts.gif"
Require breath

Set Width 1920
Set Height 1200
Set FontSize 18
Set FontFamily "JetBrainsMono Nerd Font"
Set Theme "Catppuccin Mocha"
Set WindowBar Colorful
Set MarginFill "#0D1117"
Set TypingSpeed 20ms

Hide
Type "breath start --theme catppuccin-mocha --font ansiShadow --breathing 1m --rounds 1"
Enter
Sleep 1.5s
Show
Screenshot .github/assets/ansiShadow.png
Sleep 250ms
Hide
Type "q"
Sleep 500ms
Type "y"
Sleep 500ms

Type "breath start --theme catppuccin-mocha --font mono12 --breathing 1m --rounds 1"
Enter
Sleep 1.5s
Show
Screenshot .github/assets/mono12.png
Sleep 250ms
Hide
Type "q"
Sleep 500ms
Type "y"
Sleep 500ms

Type "breath start --theme catppuccin-mocha --font ansi --breathing 1m --rounds 1"
Enter
Sleep 1.5s
Show
Screenshot .github/assets/ansi.png
Sleep 250ms
Hide
Type "q"
Sleep 500ms
Type "y"
Sleep 500ms

Type "breath start --theme catppuccin-mocha --font rebel --breathing 1m --rounds 1"
Enter
Sleep 1.5s
Show
Screenshot .github/assets/rebel.png
Sleep 250ms
Hide
Type "q"
Sleep 500ms
Type "y"
Sleep 500ms
